on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:

name: Test on Windows
jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dereignis_tests=ON && cmake --build . --config Debug"

      - name: Run Tests
        run: "D:\\a\\ereignis\\ereignis\\build\\Debug\\tests\\ereignis-tests"
